### ISSUE TITLE
Unable to Launch Instances from Profiles Using Known Good AMIs

### ISSUE THREAD

**Issue by signalconductor** [tedivm/nebula#16]
I've deployed Nebula on AWS in the `us-west-2` region successfully. However, I'm encountering an issue when attempting to launch an instance from a profile. The `nebula_worker_1` logs display the error:

```
botocore.exceptions.ClientError: An error occurred (InvalidAMIID.NotFound) when calling the RunInstances operation: The image id '[ami-0efcece6bed30fd98]' does not exist
```

Interestingly, using the command `aws ec2 describe-images --image-ids ami-0efcece6bed30fd98` successfully describes the AMI.

I've confirmed the following:
- The region `us-west-2` is specified in `settings.dist.yaml`.
- `us-west-2` is set as the default region in `aws configure`.
- The instance profile has permissions to describe AMIs.
- Tried with multiple AMIs available in `us-west-2`.

I'm at a loss for what might be causing this. Any help would be appreciated!

**Comment by tedivm** [comment]
The error message is saying that the AMI is `[ami-0efcece6bed30fd98]`, but it should be `ami-0efcece6bed30fd98`. It looks like there are additional characters being added in. Can you take a screenshot of what the profile looks like and post it here?

**Comment by signalconductor** [comment]
Hi @tedivm , thanks for the response! Here is a screenshot of the profile. I tried again making sure to strip any formatting (since I'm copy + pasting the AMI ID from the AWS console), but still am getting the same results. 

I did find this indicating that the brackets in the error message may be a known issue with boto3: https://github.com/boto/boto3/issues/2927, but should not effect the request. 

![2023-11-04 11_46_23-nebula](https://github.com/tedivm/nebula/assets/47067289/d2f9e69c-3c31-4a0c-909d-b7e9bfbfded6)

**Comment by tedivm** [comment]
Can you put the full error in, with a stack trace and line number? I'd like to see which call is causing this.

You can also use launch templates instead of profiles, which might be better. If the launch template has the site name as a tag with the value of true (by default the sitename is nebula, so the `nebula` tag set to the string `true`) then Nebula will pick up the launch templates instead. This is really useful if you're deploying it with something like Terraform, or want to make really big custom changes.

**Comment by signalconductor** [comment]
Hey @tedivm , see below:

`[2023-11-05 07:11:49,533: INFO/MainProcess] Connected to amqp://guest:**@rabbitmq:5672//
[2023-11-05 07:11:49,557: INFO/MainProcess] celery@b6f5bfc66a24 ready.
[2023-11-05 07:12:44,893: INFO/Beat] Scheduler: Sending due task AWS Scheduled Shutdowns (nebula.services.aws.shutdown_expired_instances)
[2023-11-05 07:12:44,901: INFO/MainProcess] Received task: nebula.services.aws.shutdown_expired_instances[cf71b2bd-ea7e-4caa-9c8e-2a44989424a1]   expires:[2023-11-05 07:13:44.894714+00:00]
[2023-11-05 07:12:45,305: INFO/ForkPoolWorker-3] Found credentials in shared credentials file: ~/.aws/credentials
[2023-11-05 07:12:46,121: INFO/ForkPoolWorker-3] Task nebula.services.aws.shutdown_expired_instances[cf71b2bd-ea7e-4caa-9c8e-2a44989424a1] succeeded in 1.2178402660000103s: None
[2023-11-05 07:13:16,568: INFO/MainProcess] Received task: nebula.services.aws.launch_instance[7bf7d345-6d3e-4d17-a210-b6c89cbaa545]   expires:[2023-11-05 07:18:16.436418+00:00]
[2023-11-05 07:13:16,569: WARNING/ForkPoolWorker-3] Launching t2.micro for admin with profile "1"
[2023-11-05 07:13:17,172: ERROR/ForkPoolWorker-3] Task nebula.services.aws.launch_instance[7bf7d345-6d3e-4d17-a210-b6c89cbaa545] raised unexpected: ClientError("An error occurred (InvalidAMIID.NotFound) when calling the RunInstances operation: The image id '[ami-0efcece6bed30fd98]' does not exist",)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 405, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 697, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/nebula/services/aws.py", line 347, in launch_instance
    raise e
  File "/app/nebula/services/aws.py", line 343, in launch_instance
    instances = ec2.create_instances(**startArgs)
  File "/usr/local/lib/python3.6/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidAMIID.NotFound) when calling the RunInstances operation: The image id '[ami-0efcece6bed30fd98]' does not exist
`

Thanks again for your help! I'm relatively new to Docker so hopefully I'm not doing something silly. I tried running the dev environment locally, but still running into the same issues. 

Is the expected behavior for Launch Templates to populate in the Launch Server section of the web app under "Profile" as long as the LT has a tag with a key of 'nebula' (if using defaults) and a value of 'true'? Interestingly this isn't happening in either my AWS environment or in my local dev environment, although no other AWS calls are erroring. Launch Templates are much better for my use case anyways!

**Comment by tedivm** [comment]
>Is the expected behavior for Launch Templates to populate in the Launch Server section of the web app under "Profile" as long as the LT has a tag with a key of 'nebula' (if using defaults) and a value of 'true'? Interestingly this isn't happening in either my AWS environment or in my local dev environment, although no other AWS calls are erroring. Launch Templates are much better for my use case anyways!

That is the expected behavior, yeah. Make sure your IAM user has permission to look up launch templates.

It looks like you also have to update the configuration to turn on launch templates with the `use_launch_templates` option under `aws`.

```yaml
aws:
  use_launch_templates: true
  subnets:
    - 'subnet-12345678'
    - 'subnet-23456789'
    - 'subnet-34567890'
  security_group: 'sg-12345678'
  auto_live: True
```

**Comment by tedivm** [comment]
I've updated the documentation for this feature so it's less hidden: https://github.com/tedivm/nebula/wiki/Launch-Profiles-and-Launch-Templates
